notifications:
  email: false

language: go
go:
  - "1.11.x"

install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

script:
  - make check-style
  - make test

before_deploy:
  - make dist

deploy:
  provider: releases
  api_key:
    secure: AQS497OfDt0HH56WjAEQ8p469dyWDd3IuGMcjCUe3INT2HcLfE8szdB08934VsCjTnA63iArUQojU1EUNB2Qkk5G3IhALrL+2dY3gz8YFDrjATqr8p2PQPlkMKfeUBxZDNuUXgP1dI+yEnhwnTM6uWWNYNJ9Ba2jELCzW3nx5e+wP24A8m78HdTe8cebBwAZlgf7UQTYK8Yls+4O25v9xwFAwJzELrQX0iQZwufdYZ0pz0zaAwepJCeCx1OdNzHAfSWNzdvsOfJQZ4cO/Kyar9otYjDpNrE7Ik+QMDVXepUWLe4DmBIZZbx8kJkcNe7RA2uBJ1sixAQaq7rKnWymoF16Km/TDTEj/HMA8EWBLH2g+Fq4PuwevhfoSohIQMYNhH3yk1nTc28You/uiBsFI6A/hPrKOpZOPnA/geZ6uO7zLJlkiiHN6yj6GMzz5daEMOpB7eMJ/zE5B7oWaFBOJx+i78qolJQq40pmKPwKeswZivgyqQw31jCEbfZ/KwKY0GNtMeAl7qXmvAO0x49LLnEORjPB08K9VFy3d2NMIy1lhtV0SZq4GNSfYuRW1Wx7lEeLT55igerFOo+UqgRErn05L5o70JeToCrzKKmoduBTc49W0hm8OfpTcwMqEsVC4L4VxHwQYPbpE/bTDzDWWJO5q698ByGyPN5xP+VWdZE=
  skip_cleanup: true
  file_glob: true
  file: "dist/com.cpanato.botserver-*.tar.gz"
  on:
    repo: cpanato/mattermost-plugin-botserver
    tags: true
